source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/yunhaiwu/ios-wj-framework-cocoapods-specs.git'
platform :ios, '7.0'

inhibit_all_warnings!

target :'WJUIRoutable-example' do

pod 'WJLoggingAPI', '>=2.0'
pod 'WJConfig', '>=2.0'

end
